I0  = imread('goldengate-02.png');
I1  = imread('goldengate-03.png');
display('ok0');
cimg0 = corner_detector(I0);
cimg1 = corner_detector(I1);
display('ok1');
[x0, y0, rmax0] = anms(cimg0, 100);
[x1, y1, rmax1] = anms(cimg1, 100);
display('ok2');
descs0 = feat_desc(I0, x0, y0);
descs1 = feat_desc(I1, x1, y1);
display('ok3');
[match] = feat_match(descs0, descs1);
display('ok3.5');
[ind,~,match_red] = find(match.*(match~=-1));
match_tab = [ind,match(ind)];
x0 = x0(match_tab(:,1));
x1 = x1(match_tab(:,2));
y0 = y0(match_tab(:,1));
y1 = y1(match_tab(:,2));
display('ok4');
[H, inlier_ind] = ransac_est_homography(x0, y0, x1, y1, 2);
display('ok5');
% visual_match( I0,I1,x0, y0, x1, y1, inlier_ind)
I0  = padarray(I0,[100,0]);
I0  = padarray(I0,[0,300],'post');
[h, w] = size(I1);
corn1 = [1,1;w,1;w,h;1,h;1,1];
[Xc, Yc] = apply_homography(H,corn1(:,1),corn1(:,2));
corn0  = [round(Xc)+0,round(Yc)+100];
[h0, w0] = size(I0);
mask  = poly2mask(corn0(:,1),corn0(:,2),h0,w0);
x_coord = 1:w0;
y_coord = 1:h0;
[x,y] = meshgrid(x_coord,y_coord);
x_seg = nonzeros(mask.*x);
y_seg = nonzeros(mask.*y);
[X_seg, Y_seg] = apply_homography(inv(H),x_seg(:)-0,y_seg(:)-100);
X_seg = min(max(X_seg,1),w);
Y_seg = min(max(Y_seg,1),h);
idx = sub2ind([h0,w0],y_seg,x_seg);
double(I0);
I0(idx) = interp2(double(I1),X_seg,Y_seg);
imshow(uint8(I0));
display('ok6');